services:
  - type: web
    name: airline-flight-app
    env: python
    plan: starter
    buildCommand: |
      python -m venv .venv
      source .venv/bin/activate && pip install --upgrade pip setuptools wheel
      source .venv/bin/activate && pip install -r requirements.txt
    startCommand: source .venv/bin/activate && gunicorn app:app
